client: changed window reload to observable
jerry-sky/cyber-city-sim pull request #19
Opened 2020-12-22 18:28 UTC by KamilMatejuk

Removed window reload when buying/upgrading building/buying cell. Instead added observable to be triggered after these actions and `city-detail.component` listens and reloads user resources.

2021-01-23 16:03 UTC, jerry-sky requested changes

2021-01-23 16:03 UTC, jerry-sky commented on client/src/app/city-detail/city-detail.component.ts
> +    this.city.refreashSignal.subscribe((data) => this.getAllData());
Why not have a `UserService` or something that handles _all_ of user’s data? Store it in a `BehaviorSubject` that can be subscribed for changes and can hold its current value.

Then, all components that need to use any user data can just subscribe to it and update the displayed information whenever an update comes — the observable (here `BehaviorSubject`) handles the notifications about changes of the data.

2021-01-23 16:03 UTC, jerry-sky commented on client/src/app/services/city.service.ts
> +  refreashSignal = this.refreashSignalSource.asObservable();
Also, I’m pretty sure it’s spelt “refresh”.

2021-01-24 23:26 UTC, KamilMatejuk commented
I think this is what you meant, now all data is stored in `BehaviorSubject` and handled by `UserService`.

2021-01-25 20:59 UTC, jerry-sky approved these changes
It still could be vastly improved, but it works, so I guess it’s alright.

2021-01-25 21:24 UTC, merged